import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const base=process.env.ANATOMIQ_TEST_URL || 'http://127.0.0.1:8091';
const credentials=JSON.parse(fs.readFileSync('.runtime/test-access.json','utf8'));
let assertions=0;
function check(value,message){assert.ok(value,message);assertions++;}
function client(){let cookie='';return async(path,method='GET',body)=>{const multipart=body instanceof FormData;const response=await fetch(base+'/api/'+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(body===undefined||multipart?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:multipart?body:JSON.stringify(body)});const received=response.headers.getSetCookie();if(received.length)cookie=received.map(c=>c.split(';')[0]).join('; ');let result;const raw=await response.text();try{result=JSON.parse(raw);}catch{throw new Error(path+' returned invalid JSON: '+raw.slice(0,300));}return {status:response.status,...result};};}
const guest=client(),teacher=client(),student=client();
check((await guest('students.php')).status===401,'Anonymous student access rejected');
check((await guest('config.php')).data.system_count===0,'Empty system count comes from database');
check((await teacher('auth/login.php','POST',credentials)).success,'Teacher login');
for(const path of ['students.php','modules.php','reports.php','dashboard/teacher-stats.php','settings.php','anatomy-content.php','achievements.php'])check((await teacher(path)).success,'Empty endpoint: '+path);
const config={school_name:'Integration School',academic_year:'Test Year',department:'Science',subject:'Biology',grade_level:'Custom Grade',recovery_contact:'School office',grade_a:'90',grade_b:'80',grade_c:'70',grade_d:'60',passing_score:'75',support_score:'60'};
check((await teacher('config.php','PUT',config)).success,'Save school settings');
check((await teacher('config.php','PUT',{grade_a:'50',grade_b:'90'})).status===422,'Inconsistent grade bands rejected');
const upload = new FormData();
upload.set('file',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')],{type:'image/png'}),'unsafe.phtml');
const uploaded=await teacher('media.php','POST',upload);
check(uploaded.success && uploaded.data.file_name.endsWith('.png'),'Upload uses a safe server-selected extension');
check((await teacher('media.php?id='+uploaded.data.media_id,'DELETE')).success,'Test upload cleaned up');
const invalidModel=new FormData();invalidModel.set('file',new Blob(['not a model']),'fake.glb');
check((await teacher('media.php','POST',invalidModel)).status===422,'Invalid GLB rejected');
check((await guest('config.php')).data.school_name===config.school_name,'Public school identity reads saved data');
check(!(await guest('auth/reset-password.php','POST',{action:'request',identifier:credentials.username})).data?.token,'Recovery never exposes tokens');
const system=await teacher('anatomy-content.php','POST',{system_name:'Test System',system_code:'test-system',color_hex:'#123456',description:'Database description',is_active:true,key_facts:{Fact:'Database fact'},structures:[{name:'Test Structure',desc:'Database structure',mesh_name:'part'}]});check(system.success,'Create anatomy content');const sid=system.data.system_id;
check((await guest('config.php')).data.system_count===1,'System count updates');
const module=await teacher('modules.php','POST',{system_id:sid,title:'Test module',description:'Fixture',status:'published'});check(module.success,'Create module');const mid=module.data.module_id;
const lesson=await teacher('lessons.php','POST',{module_id:mid,title:'Test lesson',lesson_type:'reading',content_text:'Database lesson body',status:'published'});check(lesson.success,'Create lesson');const lid=lesson.data.lesson_id;
const draft=await teacher('lessons.php','POST',{module_id:mid,title:'Draft lesson',lesson_type:'reading',content_text:'Hidden content',status:'draft'});check(draft.success,'Create draft');
const password='student-test-'+Date.now();const created=await teacher('students.php','POST',{username:'fixture-student',full_name:'Test Student',school_id:'TEST-STUDENT',section:'Custom Section',grade_level:'Custom Grade',school_year:'Test Year',password});check(created.success,'Create student with explicit profile');const uid=created.data.user_id;
check((await student('auth/login.php','POST',{username:'fixture-student',password})).success,'Student login');
check((await student('lessons.php?id='+draft.data.lesson_id)).status===403,'Draft content denied');
check((await student('config.php','PUT',config)).status===403,'Student cannot edit school settings');
check((await student('lessons.php?id='+lid)).data.content_text==='Database lesson body','Published lesson content');
check((await student('progress.php','POST',{lesson_id:lid,status:'completed',completion_pct:500})).status===422,'Progress percentage validated');
check((await student('progress.php','POST',{lesson_id:lid,status:'completed',completion_pct:100,time_spent_secs:999999})).success,'Completion saved with bounded study time');
const progress=await student('progress.php');check(progress.data.summary.completed_lessons===1 || Number(progress.data.summary.completed_lessons)===1,'Completion reflected in summary');check(Number(progress.data.summary.total_time_hours)<1,'Forged study time not accepted');
const assessment=await teacher('assessments.php','POST',{title:'Test quiz',system_id:sid,module_id:mid,status:'active',time_limit_mins:10,max_attempts:2,passing_score:75});check(assessment.success,'Create assessment');const aid=assessment.data.assessment_id;
const identification=await teacher('questions.php','POST',{assessment_id:aid,question_type:'identification',question_text:'Type the fixture term',hotspot_data:{target_label:'SecretTerm'},options:[{option_text:'SecretTerm',is_correct:true}],points:1});check(identification.success,'Create identification');
const mc=await teacher('questions.php','POST',{assessment_id:aid,question_type:'multiple_choice',question_text:'Choose one',points:1,options:[{option_text:'Correct fixture option',is_correct:true},{option_text:'Incorrect fixture option',is_correct:false}]});check(mc.success,'Create multiple choice');
const hot=await teacher('questions.php','POST',{assessment_id:aid,question_type:'hotspot',question_text:'Click the marked region',points:1,hotspot_data:{target_label:'Region',image_url:'/test-image.png',x:.4,y:.6,radius:.05}});check(hot.success,'Create configured hotspot');
const bank=await student('questions.php?assessment_id='+aid);check(!JSON.stringify(bank.data).includes('SecretTerm'),'Identification key omitted entirely');check(bank.data.find(q=>q.question_type==='hotspot').hotspot_data.x===undefined,'Hotspot answer coordinates omitted');
const full=await student('assessments.php?id='+aid);check(!JSON.stringify(full.data).includes('SecretTerm'),'Assessment endpoint hides identification key');
const attempt=await student('quiz/start.php','POST',{assessment_id:aid});check(attempt.success,'Start attempt');check(attempt.data.remaining_seconds<=600,'Server deadline returned');const subid=attempt.data.submission_id;
const correctBank=await teacher('questions.php?assessment_id='+aid);const correctOption=correctBank.data.find(q=>q.question_id===mc.data.question_id).options.find(o=>o.is_correct).option_id;
const answers=[{question_id:identification.data.question_id,response_text:'SecretTerm'},{question_id:mc.data.question_id,selected_option:correctOption},{question_id:hot.data.question_id,hotspot_clicked:{x:.4,y:.6}}];
check((await student('quiz/save.php','POST',{submission_id:subid,answers})).success,'Save draft');
const resumed=await student('quiz/start.php','POST',{assessment_id:aid});check(resumed.data.submission_id===subid && resumed.data.answers.length===3,'Resume restores same attempt and answers');
check((await teacher('questions.php?id='+mc.data.question_id,'DELETE')).status===409,'Questions locked once attempted');
const graded=await student('quiz/submit.php','POST',{submission_id:subid,answers,time_taken_secs:999999});check(graded.success && graded.data.score===100,'Server grades all three question types');check(graded.data.time_taken_secs<100,'Server calculates elapsed time');
const duplicate=await student('quiz/submit.php','POST',{submission_id:subid,answers:[]});check(duplicate.success && duplicate.data.score===100,'Submission retry is idempotent');
check((await student('quiz/result.php?submission_id='+subid)).data.responses.length===3,'Historical responses preserved');
const second=await student('quiz/start.php','POST',{assessment_id:aid});check(second.success,'Second attempt');
check((await student('quiz/save.php','POST',{submission_id:second.data.submission_id,answers:[answers[0]]})).success,'Save partial attempt');
execFileSync(process.env.PHP_BINARY||(fs.existsSync('C:/xampp/php/php.exe')?'C:/xampp/php/php.exe':'php'),['tests/database.php','expire'],{stdio:'pipe'});
check((await student('quiz/save.php','POST',{submission_id:second.data.submission_id,answers})).status===409,'Expired attempts cannot save new answers');
const expired=await student('quiz/submit.php','POST',{submission_id:second.data.submission_id,answers});check(expired.success && expired.data.score===33.33,'Late submission grades only pre-deadline answers');
check((await student('quiz/start.php','POST',{assessment_id:aid})).status===403,'Attempt limit enforced');
const report=await teacher('reports.php');check(report.success && report.data.score_trend.length===1,'Trend uses real dates');
const notice=await teacher('announcements.php','POST',{title:'Custom section notice',body:'For this class only',category:'general',audience:'section:Custom Section'});
check(notice.success,'Announcements support arbitrary database section names');
check((await student('announcements.php')).data.announcements.some(a=>a.title==='Custom section notice'),'Section announcement reaches its student');
const notifications=await student('notifications.php');
const scoreNotice=notifications.data.find(n=>n.id.startsWith('score:'));
check(Boolean(scoreNotice),'Score notification uses a distinct database identifier');
check((await student('notifications/mark-read.php','POST',{id:scoreNotice.id})).success,'Mark notification read');
await student('auth/logout.php','POST');await student('auth/login.php','POST',{username:'fixture-student',password});
check(!(await student('notifications.php')).data.find(n=>n.id===scoreNotice.id).unread,'Notification read state survives logout');
await teacher('students.php?id='+uid,'PUT',{section:'Different Section'});
check(!(await student('announcements.php')).data.announcements.some(a=>a.title==='Custom section notice'),'Another section cannot see the announcement');
check((await student('notifications/mark-read.php','POST',{id:'announcement:'+notice.data.announcement_id})).status===404,'Cannot mark another section notification as read');
await teacher('students.php?id='+uid,'PUT',{section:'Custom Section'});
await student('anatomy-content.php');
const exploration=await student('analytics/exploration.php','POST',{system_id:sid,duration_secs:999999,interactions:999999});
check(exploration.success && exploration.data.duration_secs<5,'Exploration time bounded by server elapsed time');
check((await teacher('achievements.php','POST',{title:'First completion',metric:'completed_lessons',threshold:1})).success,'Create configurable goal');
check((await student('dashboard/student-stats.php')).data.achievements[0].earned,'Database goal evaluated');
check((await teacher('students.php?id='+uid,'PUT',{is_active:false})).success,'Deactivate student');
check((await student('scores.php')).status===401,'Existing session denied immediately after deactivation');
check((await teacher('students.php?id='+uid,'PUT',{is_active:true})).success,'Reactivate test student');
check((await student('auth/login.php','POST',{username:'fixture-student',password})).success,'Student signs in again');
check((await teacher('auth/reset-password.php','POST',{action:'teacher_reset',student_id:uid,new_password:'replacement-test-password'})).success,'Teacher-managed reset');
check((await student('auth/session.php')).status===401,'Password reset revokes existing sessions');
for(const path of ['/database/reset_student_progress.php','/database/schema.php','/.runtime/test-access.json'])check((await fetch(base+path)).status===404,'Private route protected: '+path);
console.log(`Integration checks passed: ${assertions}`);
